[doctor]

checks = [
  { check = "homebrew" },
  { check = "tool-versions", command = "plugin-installed", args = { plugin = "rust" } },
  { check = "tool-versions", command = "package-installed", args = { plugin = "rust" } },
  { check = "rust", command = "crate-installed", args = { name = "cargo-audit" } },
  { check = "rust", command = "crate-installed", args = { name = "cargo-outdated" } },
  { check = "rust", command = "target-installed", args = { target = "aarch64-apple-darwin" } },
  { check = "rust", command = "target-installed", args = { target = "x86_64-apple-darwin" } },
]

[test]

checks = [
  { name = "Check for warnings", shell = "cargo build --workspace --features strict" },
  { step = "rust", command = "test", verbose = true },
]

[audit]

checks = [
  ## chrono and time have known potential segfaults
  { name = "Audit crates", shell = "cargo audit", allow_failure = true, verbose = true },
  { check = "rust", command = "format-check" },
  { name = "Check md format", shell = "bin/dev/format-md --check", remedy = "bin/dev/format-md --all" },
  { step = "rust", command = "clippy" },
]

[update]

steps = [
  { step = "git", command = "pull" },
  { doctor = {} },
]

[shipit]

steps = [
  { audit = {} },
  { update = {} },
  { test = {} },
  { name = "Release", shell = "bin/dev/release", verbose = true },
  { step = "git", command = "push" },
  { step = "github", command = "link-to-actions", verbose = true },
]
